
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CUCMarca.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Area
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Area()
    {

        this.FuncionarioArea = new HashSet<FuncionarioArea>();

    }


    public int AreaID { get; set; }

    public string Nombre { get; set; }

    public int TipoAreaID { get; set; }

    public Nullable<int> Jefe { get; set; }



    public virtual Funcionario Funcionario { get; set; }

    public virtual TipoArea TipoArea { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FuncionarioArea> FuncionarioArea { get; set; }

}

}
