
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CUCMarca.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Excepcion
{

    public int ExcepcionID { get; set; }

    public System.DateTime FechaExcepcion { get; set; }

    public string CodigoFuncionario { get; set; }

    public int Estado { get; set; }

    public int AutorizadoPor { get; set; }

    public System.DateTime FechaAutorizacion { get; set; }

    public string Observaciones { get; set; }

    public int MotivoID { get; set; }

    public bool ReponeTiempo { get; set; }

    public Nullable<System.DateTime> FechaReposicion { get; set; }



    public virtual FuncionarioArea FuncionarioArea { get; set; }

    public virtual Motivo Motivo { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
