
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CUCMarca.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FuncionarioArea
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FuncionarioArea()
    {

        this.Asistencia = new HashSet<Asistencia>();

        this.Excepcion = new HashSet<Excepcion>();

        this.Horario = new HashSet<Horario>();

        this.Inconsistencia = new HashSet<Inconsistencia>();

        this.Justificacion = new HashSet<Justificacion>();

    }


    public string CodigoFuncionario { get; set; }

    public int FuncionarioID { get; set; }

    public int AreaID { get; set; }



    public virtual Area Area { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asistencia> Asistencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Excepcion> Excepcion { get; set; }

    public virtual Funcionario Funcionario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Horario> Horario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Inconsistencia> Inconsistencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Justificacion> Justificacion { get; set; }

}

}
