
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CUCMarca.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Horario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Horario()
    {

        this.HorarioDetalle = new HashSet<HorarioDetalle>();

        this.Inconsistencia = new HashSet<Inconsistencia>();

    }


    public int HorarioId { get; set; }

    public byte Cuatrimestre { get; set; }

    public int Anio { get; set; }

    public byte Estado { get; set; }

    public string CodigoFuncionario { get; set; }



    public virtual FuncionarioArea FuncionarioArea { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HorarioDetalle> HorarioDetalle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Inconsistencia> Inconsistencia { get; set; }

}

}
