
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CUCMarca.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Justificacion
{

    public int JustificacionID { get; set; }

    public int InconsistenciaID { get; set; }

    public string CodigoFuncionario { get; set; }

    public bool ReponeTiempo { get; set; }

    public Nullable<System.DateTime> FechaReposicion { get; set; }

    public string Observaciones { get; set; }

    public System.DateTime FechaJustificacion { get; set; }

    public int MotivoID { get; set; }

    public Nullable<int> AutorizadoPor { get; set; }

    public Nullable<System.DateTime> FechaAutorizacion { get; set; }

    public string Estado { get; set; }



    public virtual FuncionarioArea FuncionarioArea { get; set; }

    public virtual Inconsistencia Inconsistencia { get; set; }

    public virtual Motivo Motivo { get; set; }

}

}
